### ISSUE TITLE
Photo resources attached

### ISSUE THREAD

**Issue by sakujajp** [DFGANDP/Rotnet-Captcha-Solver#1]
Hello, can you send me the photo resources attached in the file. Thank you
![captcha_solver](https://github.com/DFGANDP/Rotnet-Captcha-Solver/assets/67476594/24127443-8e8a-4720-a734-7d60d5820dec)

**Comment by DFGANDP** [comment]
Hi, sure

https://drive.google.com/file/d/1vpy6ty9x2zWN2o8Gj3clB2BSGRP-Chiv/view?usp=sharing

**Comment by sakujajp** [comment]
> Hi, sure
> 
> https://drive.google.com/file/d/1vpy6ty9x2zWN2o8Gj3clB2BSGRP-Chiv/view?usp=sharing

Thank you so much
